plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.5.1.cjs

packageExtensions:
  react-scripts@*:
    peerDependencies:
      eslint-config-react-app: '*'
